src/main/java/br/ufpi/carrinhocompras/model/Cliente.java
package br.ufpi.carrinhocompras.model; 

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

@Entity
public class Cliente implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	private Long cpf;
	private String nome;
	private String email;
	private String genero;

	@Temporal(TemporalType.DATE)
	private Date dataNascimento;

	private String telefone;

	@Embedded
	private Endereco endereco;

	private String senha;

	@OneToMany(mappedBy = "cliente")
	private List<Compra> compras;

	@Version
	private int versao;

	public Cliente() {

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCpf() {
		return cpf;
	}

	public void setCpf(Long cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public Endereco getEndereco() {
		return endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}

src/main/java/br/ufpi/carrinhocompras/model/Compra.java
/**
 * 
 */
package br.ufpi.carrinhocompras.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Compra implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	private double valor;

	@ManyToOne
	private Cliente cliente;

	@Temporal(TemporalType.TIMESTAMP)
	private Date data;

	@OneToMany(mappedBy = "compra")
	private List<ItemCompra> produtos;

	private String tipoPagamento;

	public Compra() {

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public List<ItemCompra> getProdutos() {
		return produtos;
	}

	public void setProdutos(List<ItemCompra> produtos) {
		this.produtos = produtos;
	}

	public String getTipoPagamento() {
		return tipoPagamento;
	}

	public void setTipoPagamento(String tipoPagamento) {
		this.tipoPagamento = tipoPagamento;
	}

	public double getValor() {
		return valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}
}

src/main/java/br/ufpi/carrinhocompras/model/Endereco.java
package br.ufpi.carrinhocompras.model;

import java.io.Serializable;

import javax.persistence.Embeddable;

@Embeddable
public class Endereco implements Serializable {

	private static final long serialVersionUID = 1L;

	private String numero;

	private String logradouro;

	private String cep;

	private String bairro;

	public Endereco() {

	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

}

src/main/java/br/ufpi/carrinhocompras/model/ItemCompra.java
/**
 * 
 */
package br.ufpi.carrinhocompras.model;
import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class ItemCompra implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@ManyToOne
	private Produto produto;

	@ManyToOne
	private Compra compra;

	private Integer quantidade;

	public ItemCompra() {

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public Compra getCompra() {
		return compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

}

src/main/java/br/ufpi/carrinhocompras/model/Produto.java
package br.ufpi.carrinhocompras.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.DecimalMax;

@Entity
public class Produto implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@DecimalMax("100.00")
	private Double precoUnitario;

	private String tipo;

	private String descricao;

	public Produto() {

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Double getPrecoUnitario() {
		return precoUnitario;
	}

	public void setPrecoUnitario(Double precoUnitario) {
		this.precoUnitario = precoUnitario;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}

src/main/java/br/ufpi/carrinhocompras/model/TipoProduto.java
package br.ufpi.carrinhocompras.model;

public enum TipoProduto {
	
	UM, DOIS, TRES

}

src/main/java/br/ufpi/carrinhocompras/controller/ClienteBean.java
package br.ufpi.carrinhocompras.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.ufpi.carrinhocompras.facade.ClienteFacade;
import br.ufpi.carrinhocompras.model.Cliente;

@Named
@RequestScoped
public class ClienteBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private ClienteFacade clienteFacade;

	private String cpf;

	private Cliente cliente;

	@PostConstruct
	private void init() {
		this.cliente = new Cliente();
	}

	public void salvar() {
		if (cpf != null) {
			cpf = cpf.replaceAll("\\.", "").replaceAll("\\-", "");
			cliente.setCpf(Long.valueOf(cpf));
			clienteFacade.salvar(this.cliente);
		}
		this.cliente = new Cliente();
		this.cpf = "";
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

}

src/main/java/br/ufpi/carrinhocompras/controller/CompraBean.java
package br.ufpi.carrinhocompras.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.event.DragDropEvent;

import br.ufpi.carrinhocompras.facade.CompraFacade;
import br.ufpi.carrinhocompras.model.Compra;
import br.ufpi.carrinhocompras.model.ItemCompra;
import br.ufpi.carrinhocompras.model.Produto;

@Named
@SessionScoped
public class CompraBean implements Serializable{

	private static final long serialVersionUID = 1L;

	private List<ItemCompra> itensCompra;
	
	private Produto produtoSelecionado;
	
	@Inject
	private UsuarioBean usuarioBean;
	
	@Inject
	private CompraFacade compraFacade;
	
	@PostConstruct
	public void init(){
		itensCompra = new ArrayList<ItemCompra>();
	}
	
	public CompraBean() {
	}
	
	public void selecionarUmProduto(DragDropEvent ddEvent){
		Produto produto = (Produto) ddEvent.getData();
		inserirNoCarrinho(produto);
	}
	
	private void inserirNoCarrinho(Produto produto){
		boolean produtoExiste = false;
		for (ItemCompra itemCompra : itensCompra) {
			if(itemCompra.getProduto().getId().equals(produto.getId())){
				itemCompra.setQuantidade(itemCompra.getQuantidade()+1);
				produtoExiste = true;
				break;
			}
		}
		if(!produtoExiste){
			ItemCompra item = new ItemCompra();
			item.setProduto(produto);
			item.setQuantidade(1);
			itensCompra.add(item);
		}
	}
	
	public void adicionarNoCarrinho(Produto produto){
		inserirNoCarrinho(produto);
	}
	
	public void remover(ItemCompra itemCompra){
		itensCompra.remove(itemCompra);
	}
	
	public void finalizarCompra(){
		Compra compra = new Compra();
		compra.setData(new Date());
		compra.setProdutos(itensCompra);
		compra.setTipoPagamento("DINHEIRO");
		compra.setCliente(usuarioBean.getUsuarioLogado());
		double valor = 0;
		for (ItemCompra itemCompra : itensCompra) {
			valor += itemCompra.getQuantidade() * itemCompra.getProduto().getPrecoUnitario();
		}
		compra.setValor(valor);
		
		compraFacade.salvarCompra(compra);
		itensCompra = new ArrayList<ItemCompra>();
		produtoSelecionado = null;
	}

	public List<ItemCompra> getItensCompra() {
		return itensCompra;
	}

	public void setItensCompra(List<ItemCompra> itensCompra) {
		this.itensCompra = itensCompra;
	}

	public Produto getProdutoSelecionado() {
		return produtoSelecionado;
	}

	public void setProdutoSelecionado(Produto produtoSelecionado) {
		this.produtoSelecionado = produtoSelecionado;
	}
	
	
}

src/main/java/br/ufpi/carrinhocompras/controller/ProdutoBean.java
package br.ufpi.carrinhocompras.controller;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

import br.ufpi.carrinhocompras.facade.ProdutoFacade;
import br.ufpi.carrinhocompras.model.Produto;

@Named
@SessionScoped
public class ProdutoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Produto produto;
	
	private LazyDataModel<Produto> produtos;

	@Inject
	private ProdutoFacade produtoFacade;
	
	@PostConstruct
	public void init(){
		produto = new Produto();
		
		produtos = new LazyDataModel<Produto>() {

			private static final long serialVersionUID = 1L;

			@Override
			public List<Produto> load(int first, int pageSize,
					String sortField, SortOrder sortOrder,
					Map<String, Object> filters) {

				this.setRowCount(produtoFacade.countProdutos());

				return produtoFacade.listarProdutosLazy(first, pageSize);
			}

		};
	}


	public ProdutoBean() {
		
	}

	public void salvar() {
		try {
			produtoFacade.salvar(produto);
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage("form:desc",
					new FacesMessage(FacesMessage.SEVERITY_ERROR,
							e.getMessage(), "detalhe da mensagem"));
		}
		cancelar();
	}
	
	public void remover(Produto produto) {
		if (produto.getId() == this.produto.getId()) {
			cancelar();
		}
		produtoFacade.deletar(produto);
	}

	public void editar(Produto produto) {
		this.produto = produto;
	}
	
	public void cancelar() {
		produto = new Produto();
	}

	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public LazyDataModel<Produto> getProdutos() {
		return produtos;
	}

	public void setProdutos(LazyDataModel<Produto> produtos) {
		this.produtos = produtos;
	}
	
}

src/main/java/br/ufpi/carrinhocompras/controller/ReportProdutoBean.java
package br.ufpi.carrinhocompras.controller;

import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import br.ufpi.carrinhocompras.facade.ProdutoFacade;

@Named
@RequestScoped
public class ReportProdutoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private ProdutoFacade produtoFacade;

	public StreamedContent getRelatorioDinamico() {
		try {
			this.produtoFacade.gerarRelatorio();
			String path = System.getProperty("java.io.tmpdir")
					+ "/Relatorio.pdf";
			java.io.File f = new java.io.File(path);
			InputStream stream = new java.io.FileInputStream(f);

			return new DefaultStreamedContent(stream, "application/pdf",
					"Relatório.pdf");
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}

		return null;
	}
	
	public StreamedContent getRelatorioIReport() {
		try {

			byte[] contentFile = this.produtoFacade.gerarRelatorioIReport();
			InputStream stream = new ByteArrayInputStream(contentFile);

			return new DefaultStreamedContent(stream, "application/pdf",
					"RelatórioDeProdutos.pdf");
		} catch (Exception e) {
			e.printStackTrace();
		}

		return null;
	}

}

src/main/java/br/ufpi/carrinhocompras/controller/UsuarioBean.java
package br.ufpi.carrinhocompras.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.Map;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import br.ufpi.carrinhocompras.facade.ClienteFacade;
import br.ufpi.carrinhocompras.model.Cliente;

@Named
@SessionScoped
public class UsuarioBean implements Serializable{

	private static final long serialVersionUID = 1L;

	@Inject
	private ClienteFacade clienteFacade;
	
	private String email;
	private String senha;

	public UsuarioBean() {
	}
	
	public void fazerLogin() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		if (getUsuarioLogado() == null) {
			Cliente cliente = clienteFacade.procurarClientePorEmailSenha(email,
					senha);
			if (cliente != null) {
				Map<String, Object> session = facesContext.getExternalContext()
						.getSessionMap();
				session.put("usuarioLogado", cliente);
				try {
					facesContext.getExternalContext().redirect("index.xhtml");
				} catch (IOException e) {
					e.printStackTrace();
				}
			} else {
				facesContext.addMessage(null, new FacesMessage(
						FacesMessage.SEVERITY_ERROR, "Erro de Login",
						"Usuario e/ou Senha incorretas"));
			}
		}
	}

	public void fazerLogout() {
		Map<String, Object> session = FacesContext.getCurrentInstance()
				.getExternalContext().getSessionMap();
		session.remove("usuarioLogado");
		HttpServletRequest request = (HttpServletRequest) FacesContext
				.getCurrentInstance().getExternalContext().getRequest();
		request.getSession().invalidate();
		try {
			FacesContext.getCurrentInstance().getExternalContext()
					.redirect("login.xhtml");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public Cliente getUsuarioLogado() {
		Map<String, Object> session = FacesContext.getCurrentInstance()
				.getExternalContext().getSessionMap();
		return (Cliente) session.get("usuarioLogado");
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}
}

src/main/webapp/cliente.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
</h:head>
<h:body>
	<p:messages id="messages" showDetail="true" />
	<h:form id="frmclientes" style="margin: 0 auto; width: 20%; margin-top: 20%">

		<p:fieldset id="fsclientes" legend="Cadastro de Cliente">
			<p:growl id="grlclientes" showDetail="true" />

			<h:panelGrid id="pgclientes" columns="2">

				<p:outputLabel id="lbemail" value="Email:" for="email" />
				<p:inputText id="email" value="#{clienteBean.cliente.email}"
					required="true" />


				<p:outputLabel id="lbsenha" value="Senha:" for="senha" />
				<p:password id="senha" value="#{clienteBean.cliente.senha}"
					required="true" />

				<p:outputLabel id="lbcpf" value="CPF:" for="cpf" />
				<p:inputMask id="cpf" value="#{clienteBean.cpf}" required="true"
					mask="999.999.999-99" />

				<p:outputLabel id="lbtelefone" value="Telefone:" for="telefone" />
				<p:inputMask id="telefone" value="#{clienteBean.cliente.telefone}"
					required="true" mask="(99) 9999-9999" />

			</h:panelGrid>

			<p:commandButton id="btnsalvar" icon="ui-icon-user" value="Salvar"
				action="#{clienteBean.salvar}" update="@form :messages" />

		</p:fieldset>

	</h:form>
</h:body>

	<script type="text/javascript" src="js/capt.mining.useskill.4-oracle.js"></script>
	<script type="text/javascript">
		//caso utilize JQuery no sistema, utilize o Jquery.ready() e o paramatro "waitdomready" = false 
		jQuery(document).ready(function(){
			try{
				useskill_capt_onthefly({
					client: "CARRINHO-COMPRAS", //nome abreviado do sistema monitorado
					version: 3, //versao do script de captura
		
// 					url: "http://easii.ufpi.br/useskill-capture/actions/create",
					url: "http://localhost:8080/oracle-test/backend/actions",
					waitdomready: false, //se for verdadeiro, aguarda o evento DOMContentLoaded ser disparado, caso contrario ja executa a captura
					sendactions: true, //enviar acoes para o servidor
					debug: true, //apresentar dados no console
					
					onthefly: true, //para scripts inseridos via onthefly
					plugin: false, //apenas para script via plugin do chrome
					
					captureback: false, //captura de eventos de voltar -> con
					capturehashchange: false, //capturar eventos de mudanca de hash
					jheat: false, //para sistemas baseados no jheat
					timetosubmit: 120, //periodicidade em segundos para envio de eventos
					
					//dados do usuario logado:
					username: "usuarioTeste", //pode ser retornado por funcao ou uma string
					role: "user", //pode ser retornado por funcao ou uma string
					oracleElements: ["#email", "#telefone", "#senha", ".cpf"]
				});
			} catch(e) {
				console.log('usability analytics stopped!');
			}
		});
	</script>
</html>

src/main/webapp/home.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<meta charset="utf-8" />
	
</h:head>

<h:body>
	<h1>PROJETO CARRINHO DE COMPRAS</h1>
	
	<h:button value="BOTÃO JSF"></h:button>
	<br/>
	<hr/>
	<p:button value="BOTÃO PRIMEFACES"></p:button>
</h:body>
</html>

src/main/webapp/produto.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" template="index.xhtml">

	<ui:define name="centro">
		<p:tabView id="tabview">
			<p:tab id="tabproduto" title="Produto">
				<h:form id="frmcadastro">

					<p:growl id="grl" showDetail="true" sticky="false" />

					<p:messages id="messages" showDetail="true" showSummary="true" />
					<p:panel id="pnprodutos" header="Informações do Produto" closable="false"
						toggleable="true" toggleSpeed="0">

						<h:panelGrid id="pgprodutos" columns="3">
							<p:outputLabel id="lbid" value="Id" for="id" />
							<p:inputText id="id" value="#{produtoBean.produto.id}"
								disabled="true" />
							<p:message id="msid" for="id" />

							<p:outputLabel id="lbdescricao" value="Descrição do Produto" for="desc" />
							<p:inputTextarea value="#{produtoBean.produto.descricao}"
								id="desc" required="true" />
							<p:message id="msdescricao" for="desc" />

							<p:outputLabel id="lbtipo" value="Tipo do Produto" for="tipo" />
							<p:selectOneMenu value="#{produtoBean.produto.tipo}" id="tipo"
								required="true">
								<f:selectItem id="sinone" noSelectionOption="true" />
								<f:selectItem id="sium" itemLabel="Um" itemValue="UM" />
								<f:selectItem id="sidois" itemLabel="Dois" itemValue="DOIS" />
								<f:selectItem id="sitres" itemLabel="Tres" itemValue="TRES" />
							</p:selectOneMenu>
							<p:message id="mstipo" for="tipo" />

							<p:outputLabel id="lbpreco" value="Preço Unitário"
								for="pUnitario" />
							<p:inputText value="#{produtoBean.produto.precoUnitario}"
								id="pUnitario" required="true" />
							<p:message id="mspreco" for="pUnitario" />
						</h:panelGrid>
					</p:panel>

					<p:spacer />

					<div id="div" style="text-align: center">
						<p:commandButton id="btnsalvar" value="Salvar"
							action="#{produtoBean.salvar}"
							update="@form :#{p:component('table')}" icon="ui-icon-disk" />
						<p:commandButton id="btncancelar" value="Cancelar"
							action="#{produtoBean.cancelar}"
							update="@form" icon="ui-icon-cancel"
							process="@this">
							<p:resetInput target="form" />
						</p:commandButton>
						
						<p:commandButton id="btnreldin" value="Relatório Dinamico" ajax="false"
							icon="ui-icon-arrowthick-1-s" immediate="true">
							<p:fileDownload value="#{reportProdutoBean.relatorioDinamico}" />
						</p:commandButton>
						
						<p:commandButton id="btnrelreport" value="Relatório IReport" ajax="false"
							icon="ui-icon-arrowthick-1-s" immediate="true">
							<p:fileDownload value="#{reportProdutoBean.relatorioIReport}" />
						</p:commandButton>
					</div>
				</h:form>
				
				<p:spacer />
				<p:dataTable var="produto" value="#{produtoBean.produtos}"
					paginator="true" rows="5" paginatorPosition="bottom" lazy="true"
					id="table">
					<f:facet name="header">
						<div style="text-align: left">
							<h:outputText id="lblista" value="Lista de Produtos" />
							: #{produtoBean.produtos.rowCount}
						</div>
					</f:facet>
					<p:column id="colopcoes" width="90" headerText="Opções"
						style="text-align:center">
						<p:commandButton id="btnremover" action="#{produtoBean.remover(produto)}"
							icon="ui-icon-trash" process="@this"
							update="table :#{p:component('frmcadastro')}" />
						<p:commandButton id="btneditar" action="#{produtoBean.editar(produto)}"
							icon="ui-icon-pencil" process="@this"
							update="table :#{p:component('frmcadastro')}" />
					</p:column>
					<p:column id="colid" headerText="Id" width="50"
						style="text-align:center" sortBy="#{produto.id}">
						<h:outputText id="lbid" value="#{produto.id}" />
					</p:column>

					<p:column id="coldesc" headerText="Descrição"
						sortBy="#{produto.descricao}">
						<h:outputText id="lbdesc" value="#{produto.descricao}" />
					</p:column>

					<p:column id="coltipo" headerText="Tipo" width="90"
						style="text-align:center" sortBy="#{produto.tipo}">
						<h:outputText id="lbtipo" value="#{produto.tipo}" />
					</p:column>

					<p:column id="colpreco" headerText="Preço"
						width="180" style="text-align:right" sortBy="#{produto.precoUnitario}">
						<h:outputText id="lbpreco" value="#{produto.precoUnitario}">
							<f:convertNumber pattern="R$ #,##0.00" />
						</h:outputText>
					</p:column>
				</p:dataTable>
			</p:tab>
		</p:tabView>
	</ui:define>
</ui:composition>